/**
 * Service to provide predefined diagram templates (HLD, LLD, DBD)
 * These diagrams are embedded directly in the component for simplicity
 */

export class DiagramDataService {
  static getFeaturesDiagram(features: any[] = [], stories: any[] = [], prompt: string = ''): string {
    const escapeMermaidId = (value: string): string => {
      return value.replace(/[^a-zA-Z0-9_]/g, '_');
    };

    const formatMermaidLabel = (value: string): string => {
      const escapeHtml = (val: string): string => {
        return val
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;')
          .replace(/`/g, '&#96;');
      };

      const trimmed = (value || '').trim();
      if (!trimmed) {
        return escapeHtml('Untitled');
      }

      const mermaidLabelMaxChars = 36;
      const words = trimmed.split(/\s+/);
      const lines: string[] = [];
      let current = '';

      words.forEach((word) => {
        const candidate = current ? `${current} ${word}` : word;
        if (candidate.length > mermaidLabelMaxChars && current) {
          lines.push(current);
          current = word;
        } else {
          current = candidate;
        }
      });

      if (current) {
        lines.push(current);
      }

      const escapedLines = lines.map((line) => escapeHtml(line));
      return escapedLines.join('<br/>');
    };

    const lines: string[] = ['graph TD'];
    const promptNode = escapeMermaidId('prompt');
    const promptLabel = formatMermaidLabel(prompt || 'Customer Request');
    lines.push(`${promptNode}["${promptLabel}"]`);

    features.forEach((feature, index) => {
      const featureId = escapeMermaidId(`feature_${index}`);
      const featureLabel = formatMermaidLabel(feature.title || `Feature ${index + 1}`);
      lines.push(`${promptNode} --> ${featureId}["${featureLabel}"]`);
      stories
        .filter((story) => story.featureTitle === feature.title)
        .forEach((story, storyIndex) => {
          const storyId = escapeMermaidId(`story_${index}_${storyIndex}`);
          const storyLabel = formatMermaidLabel(story.userStory || `Story ${storyIndex + 1}`);
          lines.push(`${featureId} --> ${storyId}["${storyLabel}"]`);
        });
    });

    if (lines.length === 1) {
      lines.push('A[No data]');
    }

    return lines.join('\n');
  }

  static getHLDDiagram(features: any[] = [], stories: any[] = [], prompt: string = ''): string {
    // Escape and format text for Mermaid
    const escapeMermaid = (text: string, maxLength: number = 50): string => {
      if (!text) return 'Not specified';
      const cleaned = text
        .replace(/[\[\](){}<>]/g, '')
        .replace(/"/g, '')
        .replace(/\n/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
      if (cleaned.length > maxLength) {
        return cleaned.substring(0, maxLength) + '...';
      }
      return cleaned || 'Not specified';
    };

    // Format prompt summary for display
    const promptSummary = escapeMermaid(prompt || 'Customer Request', 60);
    
    // Generate feature nodes dynamically
    let featureNodes = '';
    let featureConnections = '';
    if (features.length > 0) {
      features.forEach((feature, idx) => {
        const featureId = `Feature${idx}`;
        const featureLabel = escapeMermaid(feature.title || `Feature ${idx + 1}`, 45);
        featureNodes += `        ${featureId}["${featureLabel}"]\n`;
        featureConnections += `    ${featureId} -->|Generated by Agent 1| Agent1\n`;
      });
    } else {
      featureNodes = '        Feature0["Feature Components"]\n';
      featureConnections = '    Feature0 -->|Generated by Agent 1| Agent1\n';
    }

    // Generate story nodes dynamically
    let storyNodes = '';
    let storyConnections = '';
    if (stories.length > 0) {
      // Group stories by feature
      const storiesByFeature: { [key: string]: any[] } = {};
      stories.forEach(story => {
        const featureTitle = story.featureTitle || 'Unassigned';
        if (!storiesByFeature[featureTitle]) {
          storiesByFeature[featureTitle] = [];
        }
        storiesByFeature[featureTitle].push(story);
      });

      let storyIdx = 0;
      Object.entries(storiesByFeature).forEach(([featureTitle, featureStories]) => {
        featureStories.forEach(story => {
          const storyId = `Story${storyIdx}`;
          const storyLabel = escapeMermaid(story.userStory || `Story ${storyIdx + 1}`, 45);
          storyNodes += `        ${storyId}["${storyLabel}"]\n`;
          
          // Connect to Agent2
          storyConnections += `    ${storyId} -->|Generated by Agent 2| Agent2\n`;
          storyIdx++;
        });
      });
    } else {
      storyNodes = '        Story0["User Story Components"]\n';
      storyConnections = '    Story0 -->|Generated by Agent 2| Agent2\n';
    }

    // Build class names for styling - each class assignment on its own line
    let featureClassList = '';
    let storyClassList = '';
    
    if (features.length > 0) {
      const featureAssignments = features.map((_, idx) => `class Feature${idx} featureClass`).join('\n    ');
      featureClassList = featureAssignments;
    }
    
    if (stories.length > 0) {
      const storyAssignments = stories.map((_, idx) => `class Story${idx} storyClass`).join('\n    ');
      storyClassList = storyAssignments;
    }

    const diagram = `graph TD
    %% ============================================
    %% Prompt Summary
    %% ============================================
    PromptNode["Project Prompt<br/>${promptSummary}"]
    
    %% ============================================
    %% User Interface Layer
    %% ============================================
    User((User/Client))
    
    subgraph Frontend["Frontend Layer - Angular 18 SPA"]
        direction TB
        WebApp["Web Application<br/>Angular Components"]
        ChatUI["Chat Interface<br/>Real-time Interaction"]
        WorkspaceUI["Workspace View<br/>Project Dashboard"]
        WizardUI["Project Wizard<br/>Setup Flow"]
        FeedbackUI["Feedback System<br/>User Ratings"]
    end
    
    %% ============================================
    %% API Gateway Layer
    %% ============================================
    APIGateway{{API Gateway<br/>FastAPI REST Server}}
    
    %% ============================================
    %% Service Layer
    %% ============================================
    subgraph BackendServices["Backend Services Layer"]
        direction TB
        ProjectService["Project Service<br/>CRUD Operations"]
        FeatureService["Feature Service<br/>Management"]
        StoryService["Story Service<br/>Management"]
        DiagramService["Diagram Service<br/>Generation"]
        FeedbackService["Feedback Service<br/>Collection"]
        StateService["State Service<br/>Persistence"]
    end
    
    %% ============================================
    %% AI Agent Layer
    %% ============================================
    subgraph AIAgents["AI Agent Pipeline - Claude Powered"]
        direction TB
        Agent1["Agent 1<br/>Feature Generator<br/>Analysis & Ideation"]
        Agent2["Agent 2<br/>Story Builder<br/>User Story Creation"]
        Agent3["Agent 3<br/>Diagram Visualizer<br/>HLD/LLD/DBD"]
    end
    
    %% ============================================
    %% Generated Features
    %% ============================================
    subgraph GeneratedFeatures["Generated Features"]
        direction TB
${featureNodes}    end
    
    %% ============================================
    %% Generated Stories
    %% ============================================
    subgraph GeneratedStories["Generated User Stories"]
        direction TB
${storyNodes}    end
    
    %% ============================================
    %% Data Layer
    %% ============================================
    subgraph DataLayer["Data Persistence Layer"]
        direction TB
        MongoDB["MongoDB Database<br/>Projects, Features,<br/>Stories, Diagrams"]
        Cache["Redis Cache<br/>Session Storage"]
    end
    
    %% ============================================
    %% External Systems
    %% ============================================
    LLMProvider["Claude AI API<br/>Anthropic Sonnet 4.5<br/>Natural Language Processing"]
    
    %% ============================================
    %% User Flow
    %% ============================================
    User -->|Accesses| WebApp
    User -->|Submits Ideas| ChatUI
    ChatUI -->|Displays| PromptNode
    User -->|Provides Feedback| FeedbackUI
    
    %% ============================================
    %% Frontend to Backend Communication
    %% ============================================
    ChatUI -->|POST /projects/create| APIGateway
    ChatUI -->|POST /features/generate| APIGateway
    ChatUI -->|POST /stories/generate| APIGateway
    ChatUI -->|POST /diagrams/generate| APIGateway
    WizardUI -->|POST /projects| APIGateway
    WorkspaceUI -->|GET /projects/:id| APIGateway
    FeedbackUI -->|POST /feedback| APIGateway
    
    %% ============================================
    %% API to Services Routing
    %% ============================================
    APIGateway -->|Routes| ProjectService
    APIGateway -->|Routes| FeatureService
    APIGateway -->|Routes| StoryService
    APIGateway -->|Routes| DiagramService
    APIGateway -->|Routes| FeedbackService
    
    %% ============================================
    %% Service to Agent Orchestration
    %% ============================================
    ProjectService -->|Triggers| Agent1
    FeatureService -->|Triggers| Agent1
    StoryService -->|Triggers| Agent2
    DiagramService -->|Triggers| Agent3
    
    %% ============================================
    %% Agent Processing Pipeline
    %% ============================================
    PromptNode ==>|Input Context| Agent1
    Agent1 ==>|LLM Request| LLMProvider
    LLMProvider ==>|Feature JSON| Agent1
${featureConnections}
    Agent1 ==>|Context Transfer| Agent2
    Agent2 ==>|LLM Request| LLMProvider
    LLMProvider ==>|Story JSON| Agent2
${storyConnections}
    Agent2 ==>|Context Transfer| Agent3
    Agent3 ==>|LLM Request| LLMProvider
    LLMProvider ==>|Mermaid Code| Agent3
    
    %% ============================================
    %% Data Persistence Flow
    %% ============================================
    ProjectService -->|Saves| MongoDB
    FeatureService -->|Saves| MongoDB
    StoryService -->|Saves| MongoDB
    DiagramService -->|Saves| MongoDB
    FeedbackService -->|Saves| MongoDB
    
    MongoDB -->|Retrieves| ProjectService
    MongoDB -->|Retrieves| FeatureService
    MongoDB -->|Retrieves| StoryService
    
    StateService -->|Caches| Cache
    Cache -->|Fast Retrieval| StateService
    
    %% ============================================
    %% Response Flow
    %% ============================================
    Agent3 -->|Results| DiagramService
    DiagramService -->|Response| APIGateway
    APIGateway -->|JSON Response| WorkspaceUI
    WorkspaceUI -->|Renders| User
    
    %% ============================================
    %% State Management Flow
    %% ============================================
    WorkspaceUI -.->|Updates| StateService
    StateService -.->|Syncs| WorkspaceUI
    FeedbackUI -.->|Logs| FeedbackService
    
    %% ============================================
    %% Styling with Enhanced Colors
    %% ============================================
    classDef userClass fill:#4a90e2,stroke:#2c5282,stroke-width:3px,color:#fff,font-weight:bold
    classDef promptClass fill:#fbbf24,stroke:#f59e0b,stroke-width:3px,color:#fff,font-weight:bold
    classDef uiLayer fill:#3b82f6,stroke:#1e40af,stroke-width:2px,color:#fff,font-weight:500
    classDef apiLayer fill:#f59e0b,stroke:#d97706,stroke-width:3px,color:#fff,font-weight:bold
    classDef serviceLayer fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef agentLayer fill:#8b5cf6,stroke:#6d28d9,stroke-width:2px,color:#fff,font-weight:500
    classDef featureClass fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef storyClass fill:#06b6d4,stroke:#0891b2,stroke-width:2px,color:#fff,font-weight:500
    classDef llmClass fill:#ef4444,stroke:#dc2626,stroke-width:3px,color:#fff,font-weight:bold
    classDef dataLayer fill:#f97316,stroke:#ea580c,stroke-width:2px,color:#fff,font-weight:500
    
    class User userClass
    class PromptNode promptClass
    class WebApp uiLayer
    class ChatUI uiLayer
    class WorkspaceUI uiLayer
    class WizardUI uiLayer
    class FeedbackUI uiLayer
    class APIGateway apiLayer
    class ProjectService serviceLayer
    class FeatureService serviceLayer
    class StoryService serviceLayer
    class DiagramService serviceLayer
    class FeedbackService serviceLayer
    class StateService serviceLayer
    class Agent1 agentLayer
    class Agent2 agentLayer
    class Agent3 agentLayer
    class LLMProvider llmClass
    class MongoDB dataLayer
    class Cache dataLayer${featureClassList ? '\n    ' + featureClassList : ''}${storyClassList ? '\n    ' + storyClassList : ''}
    
    style Frontend fill:#dbeafe,stroke:#3b82f6,stroke-width:2px,stroke-dasharray:5 5
    style BackendServices fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5
    style AIAgents fill:#ede9fe,stroke:#8b5cf6,stroke-width:2px,stroke-dasharray:5 5
    style GeneratedFeatures fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5
    style GeneratedStories fill:#cffafe,stroke:#06b6d4,stroke-width:2px,stroke-dasharray:5 5
    style DataLayer fill:#fed7aa,stroke:#f97316,stroke-width:2px,stroke-dasharray:5 5`;

    return diagram;
  }

  static getLLDDiagram(features: any[] = [], stories: any[] = [], prompt: string = ''): string {
    // Escape text for Mermaid - ensure proper formatting
    const escapeMermaid = (text: string): string => {
      if (!text) return 'Untitled';
      // Remove special Mermaid characters and truncate
      const cleaned = text
        .replace(/[\[\](){}<>\"]/g, '')
        .replace(/\n/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .substring(0, 45);
      return cleaned || 'Untitled';
    };

    // Generate feature components based on actual features
    let featureComponents = '';
    let featureConnections = '';
    
    if (features.length > 0) {
      features.forEach((feature, idx) => {
        const featureId = `Feature${idx + 1}`;
        const featureName = escapeMermaid(feature.title || `Feature ${idx + 1}`);
        featureComponents += `        ${featureId}[${featureName}]\n`;
        featureConnections += `    AppRoot --> ${featureId}\n`;
      });
    } else {
      featureComponents = '        Feature1[Feature Component]\n';
      featureConnections = '    AppRoot --> Feature1\n';
    }

    // Generate story components based on actual stories
    let storyComponents = '';
    let storyConnections = '';
    
    if (stories.length > 0) {
      stories.forEach((story, idx) => {
        const storyId = `Story${idx + 1}`;
        const storyName = escapeMermaid(story.userStory || `Story ${idx + 1}`);
        storyComponents += `        ${storyId}[${storyName}]\n`;
        
        // Find parent feature
        if (features.length > 0) {
          const featureIdx = features.findIndex(f => f.title === story.featureTitle);
          if (featureIdx >= 0) {
            storyConnections += `    Feature${featureIdx + 1} --> ${storyId}\n`;
          } else {
            storyConnections += `    AppRoot --> ${storyId}\n`;
          }
        } else {
          storyConnections += `    Feature1 --> ${storyId}\n`;
        }
      });
    }

    // Build feature and story class names for styling - individual class assignments
    let featureClassAssignments = '';
    let storyClassAssignments = '';
    
    if (features.length > 0) {
      featureClassAssignments = features.map((_, idx) => `class Feature${idx + 1} featureComponent`).join('\n    ');
    }
    
    if (stories.length > 0) {
      storyClassAssignments = stories.map((_, idx) => `class Story${idx + 1} storyComponent`).join('\n    ');
    }

                return `graph TD
    %% ============================================
    %% Root Component
    %% ============================================
    AppRoot["App Root Component<br/>Angular 18 Main Entry<br/>State & Routing"]
    
    %% ============================================
    %% Main UI Components
    %% ============================================
    subgraph MainUI["Main User Interface Components"]
        direction TB
        ChatComponent["Chat Component<br/>Real-time Messaging<br/>Agent Interaction"]
        WorkspaceComponent["Workspace View<br/>Project Dashboard<br/>Mermaid Editor"]
        WizardComponent["Project Wizard<br/>Multi-step Form<br/>Validation"]
        FeedbackComponent["Feedback Chatbot<br/>Rating & Comments<br/>Regeneration"]
    end
    
    %% ============================================
    %% Feature Components
    %% ============================================
    subgraph Features["Feature Components"]
        direction TB
${featureComponents}    end
    
    %% ============================================
    %% Story Components
    %% ============================================
    subgraph Stories["Story Components"]
        direction TB
${storyComponents}    end
    
    %% ============================================
    %% State Signals Angular 18
    %% ============================================
    subgraph StateSignals["State Signals - Angular Reactive"]
        direction TB
        ChatState["Chat Messages Signal<br/>Observable Stream"]
        FeaturesState["Features Signal<br/>Array State"]
        StoriesState["Stories Signal<br/>Array State"]
        DiagramsState["Diagrams Signal<br/>Mermaid Source"]
        ProjectState["Project Signal<br/>Current Project"]
    end
    
    %% ============================================
    %% Frontend Services
    %% ============================================
    subgraph Services["Angular Services Layer"]
        direction TB
        AgentService["Agent Service<br/>HTTP Client<br/>API Integration"]
        DesignService["Design Service<br/>HLD/LLD/DBD<br/>Generation"]
        FeedbackService["Feedback Service<br/>Rating Collection<br/>Regeneration API"]
        LocalStorageService["LocalStorage Service<br/>Browser Persistence<br/>Session State"]
        StateService["State Service<br/>Global State<br/>Signal Management"]
        DiagramDataService["Diagram Data Service<br/>Mermaid Templates<br/>Static Diagrams"]
    end
    
    %% ============================================
    %% Backend API Routers
    %% ============================================
    subgraph BackendAPI["FastAPI Backend - Python Routers"]
        direction TB
        ProjectRouter["Project Router<br/>/api/projects"]
        FeatureRouter["Feature Router<br/>/api/features"]
        StoryRouter["Story Router<br/>/api/stories"]
        DiagramRouter["Diagram Router<br/>/api/diagrams"]
        FeedbackRouter["Feedback Router<br/>/api/feedback"]
    end
    
    %% ============================================
    %% Component Hierarchy
    %% ============================================
    AppRoot --> ChatComponent
    AppRoot --> WorkspaceComponent
    AppRoot --> WizardComponent
    AppRoot --> FeedbackComponent
    
    WorkspaceComponent --> Features
    WorkspaceComponent --> Stories
    
    %% ============================================
    %% Feature and Story Connections
    %% ============================================
${featureConnections}${storyConnections}
    
    %% ============================================
    %% State Signal Connections
    %% ============================================
    AppRoot -.->|Manages| ChatState
    AppRoot -.->|Manages| FeaturesState
    AppRoot -.->|Manages| StoriesState
    AppRoot -.->|Manages| DiagramsState
    AppRoot -.->|Manages| ProjectState
    
    ChatComponent -.->|Reads/Writes| ChatState
    ChatComponent -.->|Emits| FeaturesState
    ChatComponent -.->|Emits| StoriesState
    
    WorkspaceComponent -.->|Reads| FeaturesState
    WorkspaceComponent -.->|Reads| StoriesState
    WorkspaceComponent -.->|Reads| DiagramsState
    
    FeedbackComponent -.->|Updates| FeaturesState
    FeedbackComponent -.->|Updates| StoriesState
    
    %% ============================================
    %% Service Connections
    %% ============================================
    AppRoot --> StateService
    AppRoot --> AgentService
    
    ChatComponent --> AgentService
    ChatComponent --> LocalStorageService
    
    WorkspaceComponent --> DesignService
    WorkspaceComponent --> DiagramDataService
    WorkspaceComponent --> LocalStorageService
    
    WizardComponent --> AgentService
    
    FeedbackComponent --> FeedbackService
    
    StateService -.->|Syncs| ChatState
    StateService -.->|Syncs| FeaturesState
    StateService -.->|Syncs| StoriesState
    StateService -.->|Syncs| DiagramsState
    StateService -.->|Syncs| ProjectState
    
    %% ============================================
    %% Service to API Connections
    %% ============================================
    AgentService -->|HTTP POST| ProjectRouter
    AgentService -->|HTTP POST| FeatureRouter
    AgentService -->|HTTP POST| StoryRouter
    
    DesignService -->|HTTP POST| DiagramRouter
    DesignService -->|HTTP GET| DiagramRouter
    
    FeedbackService -->|HTTP POST| FeedbackRouter
    
    %% ============================================
    %% Enhanced Styling with Colors
    %% ============================================
    classDef rootComponent fill:#7c3aed,stroke:#5b21b6,stroke-width:4px,color:#fff,font-weight:bold
    classDef uiComponent fill:#3b82f6,stroke:#1e40af,stroke-width:2px,color:#fff,font-weight:500
    classDef featureComponent fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef storyComponent fill:#f59e0b,stroke:#d97706,stroke-width:2px,color:#fff,font-weight:500
    classDef stateSignal fill:#8b5cf6,stroke:#6d28d9,stroke-width:2px,color:#fff,font-weight:500
    classDef service fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef api fill:#ef4444,stroke:#dc2626,stroke-width:3px,color:#fff,font-weight:bold
    
    class AppRoot rootComponent
    class ChatComponent uiComponent
    class WorkspaceComponent uiComponent
    class WizardComponent uiComponent
    class FeedbackComponent uiComponent${featureClassAssignments ? '\n    ' + featureClassAssignments : ''}${storyClassAssignments ? '\n    ' + storyClassAssignments : ''}
    class ChatState stateSignal
    class FeaturesState stateSignal
    class StoriesState stateSignal
    class DiagramsState stateSignal
    class ProjectState stateSignal
    class AgentService service
    class DesignService service
    class FeedbackService service
    class LocalStorageService service
    class StateService service
    class DiagramDataService service
    class ProjectRouter api
    class FeatureRouter api
    class StoryRouter api
    class DiagramRouter api
    class FeedbackRouter api
    
    style MainUI fill:#dbeafe,stroke:#3b82f6,stroke-width:2px,stroke-dasharray:5 5
    style Features fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5
    style Stories fill:#fef3c7,stroke:#f59e0b,stroke-width:2px,stroke-dasharray:5 5
    style StateSignals fill:#ede9fe,stroke:#8b5cf6,stroke-width:2px,stroke-dasharray:5 5
    style Services fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5
    style BackendAPI fill:#fecaca,stroke:#ef4444,stroke-width:2px,stroke-dasharray:5 5`;
  }

  static getDBDDiagram(features: any[] = [], stories: any[] = []): string {
    // Enhanced DBD generation based on features and stories
    let dynamicEntities = '';
    let dynamicRelationships = '';
    
    // Add feature-related tables if features exist
    if (features.length > 0) {
      dynamicEntities += `
    
    FEATURE_DETAILS {
        uuid id PK
        uuid feature_id FK
        text problem_statement
        text business_objective
        text user_persona
        json success_metrics
        timestamp created_at
    }
    
    FEATURE_TAGS {
        uuid id PK
        uuid feature_id FK
        varchar tag_name
        varchar category
        timestamp created_at
    }`;
      
      dynamicRelationships += `
    FEATURES ||--o| FEATURE_DETAILS : has
    FEATURES ||--o{ FEATURE_TAGS : tagged_with`;
    }
    
    // Add story-related tables if stories exist
    if (stories.length > 0) {
      dynamicEntities += `
    
    STORY_IMPLEMENTATIONS {
        uuid id PK
        uuid story_id FK
        text implementation_step
        int step_order
        varchar status
        timestamp completed_at
    }
    
    STORY_TASKS {
        uuid id PK
        uuid story_id FK
        varchar task_name
        text description
        varchar status
        int estimated_hours
        timestamp created_at
    }`;
      
      dynamicRelationships += `
    STORIES ||--o{ STORY_IMPLEMENTATIONS : implements
    STORIES ||--o{ STORY_TASKS : breaks_into`;
    }

    return `erDiagram
    USERS ||--o{ PROJECTS : owns
    PROJECTS ||--o{ FEATURES : includes
    PROJECTS ||--o{ STORIES : contains
    PROJECTS ||--o{ DIAGRAMS : has
    PROJECTS ||--o{ FEEDBACK : receives
    FEATURES ||--o{ STORIES : generates${dynamicRelationships}
    
    USERS {
        uuid id PK
        varchar email UK
        varchar password_hash
        varchar full_name
        varchar role
        timestamp created_at
        timestamp updated_at
    }
    
    PROJECTS {
        uuid id PK
        uuid owner_id FK
        varchar name
        text idea_prompt
        varchar status
        varchar methodology
        varchar industry
        json metadata
        timestamp created_at
        timestamp updated_at
    }
    
    FEATURES {
        uuid id PK
        uuid project_id FK
        varchar title
        text description
        json acceptance_criteria
        varchar source
        varchar status
        int priority
        varchar run_id
        timestamp created_at
        timestamp updated_at
    }
    
    STORIES {
        uuid id PK
        uuid feature_id FK
        uuid project_id FK
        text user_story
        json acceptance_criteria
        json implementation_notes
        varchar status
        int story_points
        varchar run_id
        timestamp created_at
        timestamp updated_at
    }
    
    DIAGRAMS {
        uuid id PK
        uuid project_id FK
        varchar diagram_type
        text mermaid_source
        json style_config
        text svg_cache
        varchar run_id
        timestamp created_at
        timestamp updated_at
    }
    
    FEEDBACK {
        uuid id PK
        uuid project_id FK
        varchar item_type
        varchar item_id
        int rating
        text comment
        json context
        timestamp created_at
    }${dynamicEntities}`;
  }
}
