/**
 * Service to provide predefined diagram templates (HLD, LLD, DBD)
 * These diagrams are embedded directly in the component for simplicity
 */

export class DiagramDataService {
  static getFeaturesDiagram(features: any[] = [], stories: any[] = [], prompt: string = ''): string {
    const escapeMermaidId = (value: string): string => {
      return value.replace(/[^a-zA-Z0-9_]/g, '_');
    };

    const formatMermaidLabel = (value: string): string => {
      const escapeHtml = (val: string): string => {
        return val
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;')
          .replace(/`/g, '&#96;');
      };

      const trimmed = (value || '').trim();
      if (!trimmed) {
        return escapeHtml('Untitled');
      }

      const mermaidLabelMaxChars = 36;
      const words = trimmed.split(/\s+/);
      const lines: string[] = [];
      let current = '';

      words.forEach((word) => {
        const candidate = current ? `${current} ${word}` : word;
        if (candidate.length > mermaidLabelMaxChars && current) {
          lines.push(current);
          current = word;
        } else {
          current = candidate;
        }
      });

      if (current) {
        lines.push(current);
      }

      const escapedLines = lines.map((line) => escapeHtml(line));
      return escapedLines.join('<br/>');
    };

    const lines: string[] = ['graph TD'];
    const promptNode = escapeMermaidId('prompt');
    const promptLabel = formatMermaidLabel(prompt || 'Customer Request');
    lines.push(`${promptNode}["${promptLabel}"]`);

    features.forEach((feature, index) => {
      const featureId = escapeMermaidId(`feature_${index}`);
      const featureLabel = formatMermaidLabel(feature.title || `Feature ${index + 1}`);
      lines.push(`${promptNode} --> ${featureId}["${featureLabel}"]`);
      stories
        .filter((story) => story.featureTitle === feature.title)
        .forEach((story, storyIndex) => {
          const storyId = escapeMermaidId(`story_${index}_${storyIndex}`);
          const storyLabel = formatMermaidLabel(story.userStory || `Story ${storyIndex + 1}`);
          lines.push(`${featureId} --> ${storyId}["${storyLabel}"]`);
        });
    });

    if (lines.length === 1) {
      lines.push('A[No data]');
    }

    return lines.join('\n');
  }

  static getHLDDiagram(features: any[] = [], stories: any[] = [], prompt: string = ''): string {
    // Escape and format text for Mermaid
    const escapeMermaid = (text: string, maxLength: number = 50): string => {
      if (!text) return 'Not specified';
      const cleaned = text
        .replace(/[\[\](){}<>]/g, '')
        .replace(/"/g, '')
        .replace(/\n/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
      if (cleaned.length > maxLength) {
        return cleaned.substring(0, maxLength) + '...';
      }
      return cleaned || 'Not specified';
    };

    // Format prompt summary for display
    const promptSummary = escapeMermaid(prompt || 'Customer Request', 60);
    
    // Generate feature nodes dynamically
    let featureNodes = '';
    let featureConnections = '';
    if (features.length > 0) {
      features.forEach((feature, idx) => {
        const featureId = `Feature${idx}`;
        const featureLabel = escapeMermaid(feature.title || `Feature ${idx + 1}`, 45);
        featureNodes += `        ${featureId}["✨ ${featureLabel}"]\n`;
        featureConnections += `    ${featureId} -->|Generated by Agent 1| Agent1\n`;
      });
    } else {
      featureNodes = '        Feature0["✨ Feature Components"]\n';
      featureConnections = '    Feature0 -->|Generated by Agent 1| Agent1\n';
    }

    // Generate story nodes dynamically
    let storyNodes = '';
    let storyConnections = '';
    if (stories.length > 0) {
      // Group stories by feature
      const storiesByFeature: { [key: string]: any[] } = {};
      stories.forEach(story => {
        const featureTitle = story.featureTitle || 'Unassigned';
        if (!storiesByFeature[featureTitle]) {
          storiesByFeature[featureTitle] = [];
        }
        storiesByFeature[featureTitle].push(story);
      });

      let storyIdx = 0;
      Object.entries(storiesByFeature).forEach(([featureTitle, featureStories]) => {
        featureStories.forEach(story => {
          const storyId = `Story${storyIdx}`;
          const storyLabel = escapeMermaid(story.userStory || `Story ${storyIdx + 1}`, 45);
          storyNodes += `        ${storyId}["📚 ${storyLabel}"]\n`;
          
          // Connect to Agent2
          storyConnections += `    ${storyId} -->|Generated by Agent 2| Agent2\n`;
          storyIdx++;
        });
      });
    } else {
      storyNodes = '        Story0["📚 User Story Components"]\n';
      storyConnections = '    Story0 -->|Generated by Agent 2| Agent2\n';
    }

    // Build class names for styling
    let featureClassList = '';
    let storyClassList = '';
    
    if (features.length > 0) {
      featureClassList = 'class ' + features.map((_, idx) => `Feature${idx}`).join(',') + ' featureClass';
    }
    
    if (stories.length > 0) {
      storyClassList = 'class ' + stories.map((_, idx) => `Story${idx}`).join(',') + ' storyClass';
    }

    const diagram = `graph TD
    %% ============================================
    %% Prompt Summary
    %% ============================================
    PromptNode["💡 Prompt Summary<br/>${promptSummary}"]
    
    %% ============================================
    %% User Interface Layer
    %% ============================================
    User((👤 User))
    
    subgraph Frontend["🎨 Frontend - Angular SPA"]
        direction TB
        WebApp(🌐 Web Application)
        ChatUI(💬 Chat Interface)
        WorkspaceUI(📊 Workspace View)
        WizardUI(🧙 Project Wizard)
    end
    
    %% ============================================
    %% API Gateway Layer
    %% ============================================
    APIGateway{{🔌 FastAPI Backend<br/>API Gateway}}
    
    %% ============================================
    %% Service Layer
    %% ============================================
    subgraph BackendServices["⚙️ Backend Services"]
        direction TB
        ProjectService[📁 Project Service]
        StateService[🔄 State Management]
    end
    
    %% ============================================
    %% AI Agent Layer
    %% ============================================
    subgraph AIAgents["🤖 AI Agent Pipeline"]
        direction TB
        Agent1["🤖 Agent 1<br/>Feature Generator"]
        Agent2["📚 Agent 2<br/>Story Builder"]
        Agent3["📈 Agent 3<br/>Diagram Visualizer"]
    end
    
    %% ============================================
    %% Generated Features
    %% ============================================
    subgraph GeneratedFeatures["✨ Generated Features"]
        direction TB
${featureNodes}    end
    
    %% ============================================
    %% Generated Stories
    %% ============================================
    subgraph GeneratedStories["📚 Generated User Stories"]
        direction TB
${storyNodes}    end
    
    %% ============================================
    %% External Systems
    %% ============================================
    LLMProvider["🧠 Claude AI / LLM Provider"]
    
    %% ============================================
    %% User Flow
    %% ============================================
    User -->|Submits Idea| ChatUI
    ChatUI -->|Displays Prompt| PromptNode
    
    %% ============================================
    %% Frontend to Backend
    %% ============================================
    ChatUI -->|POST /agent/features| APIGateway
    ChatUI -->|POST /agent/stories| APIGateway
    ChatUI -->|POST /agent/visualizer| APIGateway
    WizardUI -->|POST /project/create| APIGateway
    
    %% ============================================
    %% Backend Processing
    %% ============================================
    APIGateway -->|Routes Request| ProjectService
    ProjectService -->|Orchestrates| Agent1
    ProjectService -->|Orchestrates| Agent2
    ProjectService -->|Orchestrates| Agent3
    
    %% ============================================
    %% Agent Processing Pipeline
    %% ============================================
    PromptNode ==>|Input| Agent1
    Agent1 ==>|Processes via| LLMProvider
    LLMProvider ==>|Returns Features| Agent1
${featureConnections}
    Agent1 ==>|Features Feed into| Agent2
    Agent2 ==>|Processes via| LLMProvider
    LLMProvider ==>|Returns Stories| Agent2
${storyConnections}
    Agent2 ==>|Stories Feed into| Agent3
    Agent3 ==>|Generates Diagrams via| LLMProvider
    
    %% ============================================
    %% Results Flow
    %% ============================================
    Agent3 -->|Returns Results| ProjectService
    ProjectService -->|Sends Response| APIGateway
    APIGateway -->|Delivers to| WorkspaceUI
    WorkspaceUI -->|Displays| User
    
    %% ============================================
    %% State Management
    %% ============================================
    WorkspaceUI -.->|Stores State| StateService
    StateService -.->|Retrieves State| WorkspaceUI
    
    %% ============================================
    %% Styling with Enhanced Colors
    %% ============================================
    classDef userClass fill:#4a90e2,stroke:#2c5282,stroke-width:3px,color:#fff,font-weight:bold
    classDef promptClass fill:#fbbf24,stroke:#f59e0b,stroke-width:3px,color:#fff,font-weight:bold
    classDef uiLayer fill:#3b82f6,stroke:#1e40af,stroke-width:2px,color:#fff,font-weight:500
    classDef apiLayer fill:#f59e0b,stroke:#d97706,stroke-width:3px,color:#fff,font-weight:bold
    classDef serviceLayer fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef agentLayer fill:#8b5cf6,stroke:#6d28d9,stroke-width:2px,color:#fff,font-weight:500
    classDef featureClass fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef storyClass fill:#06b6d4,stroke:#0891b2,stroke-width:2px,color:#fff,font-weight:500
    classDef llmClass fill:#ef4444,stroke:#dc2626,stroke-width:3px,color:#fff,font-weight:bold
    
    class User userClass
    class PromptNode promptClass
    class WebApp,ChatUI,WorkspaceUI,WizardUI uiLayer
    class APIGateway apiLayer
    class ProjectService,StateService serviceLayer
    class Agent1,Agent2,Agent3 agentLayer
    class LLMProvider llmClass
    
    ${featureClassList}
    ${storyClassList}
    
    style Frontend fill:#dbeafe,stroke:#3b82f6,stroke-width:2px,stroke-dasharray:5 5
    style BackendServices fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5
    style AIAgents fill:#ede9fe,stroke:#8b5cf6,stroke-width:2px,stroke-dasharray:5 5
    style GeneratedFeatures fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5
    style GeneratedStories fill:#cffafe,stroke:#06b6d4,stroke-width:2px,stroke-dasharray:5 5`;

    return diagram;
  }

  static getLLDDiagram(features: any[] = [], stories: any[] = [], prompt: string = ''): string {
    // Escape text for Mermaid - ensure proper formatting
    const escapeMermaid = (text: string): string => {
      if (!text) return 'Untitled';
      // Remove special Mermaid characters and truncate
      const cleaned = text
        .replace(/[\[\](){}<>\"]/g, '')
        .replace(/\n/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .substring(0, 45);
      return cleaned || 'Untitled';
    };

    // Generate feature components based on actual features
    let featureComponents = '';
    let featureConnections = '';
    
    if (features.length > 0) {
      features.forEach((feature, idx) => {
        const featureId = `Feature${idx + 1}`;
        const featureName = escapeMermaid(feature.title || `Feature ${idx + 1}`);
        featureComponents += `        ${featureId}[${featureName}]\n`;
        featureConnections += `    AppRoot --> ${featureId}\n`;
      });
    } else {
      featureComponents = '        Feature1[Feature Component]\n';
      featureConnections = '    AppRoot --> Feature1\n';
    }

    // Generate story components based on actual stories
    let storyComponents = '';
    let storyConnections = '';
    
    if (stories.length > 0) {
      stories.forEach((story, idx) => {
        const storyId = `Story${idx + 1}`;
        const storyName = escapeMermaid(story.userStory || `Story ${idx + 1}`);
        storyComponents += `        ${storyId}[${storyName}]\n`;
        
        // Find parent feature
        if (features.length > 0) {
          const featureIdx = features.findIndex(f => f.title === story.featureTitle);
          if (featureIdx >= 0) {
            storyConnections += `    Feature${featureIdx + 1} --> ${storyId}\n`;
          } else {
            storyConnections += `    AppRoot --> ${storyId}\n`;
          }
        } else {
          storyConnections += `    Feature1 --> ${storyId}\n`;
        }
      });
    }

    // Build feature and story class names for styling
    let featureClassNames = '';
    let storyClassNames = '';
    
    if (features.length > 0) {
      featureClassNames = features.map((_, idx) => `Feature${idx + 1}`).join(',');
    }
    
    if (stories.length > 0) {
      storyClassNames = stories.map((_, idx) => `Story${idx + 1}`).join(',');
    }

    return `graph TD
    %% ============================================
    %% Root Component
    %% ============================================
    AppRoot["🏠 App Root Component<br/>State Management"]
    
    %% ============================================
    %% Main UI Components
    %% ============================================
    subgraph MainUI["🎨 Main User Interface"]
        direction TB
        ChatComponent("💬 Chat Component")
        WorkspaceComponent("📊 Workspace View")
        WizardComponent("🧙 Project Wizard")
    end
    
    %% ============================================
    %% Feature Components
    %% ============================================
    subgraph Features["✨ Feature Components"]
        direction TB
${featureComponents}    end
    
    %% ============================================
    %% Story Components
    %% ============================================
    subgraph Stories["📚 Story Components"]
        direction TB
${storyComponents}    end
    
    %% ============================================
    %% State Signals
    %% ============================================
    subgraph StateSignals["⚡ State Signals"]
        direction TB
        ChatState("💬 Chat Messages")
        FeaturesState("✨ Features")
        StoriesState("📚 Stories")
        DiagramsState("📈 Diagrams")
    end
    
    %% ============================================
    %% Services
    %% ============================================
    subgraph Services["🔧 Angular Services"]
        direction TB
        AgentService["🌐 Agent Service"]
        LocalStorageService["💾 LocalStorage Service"]
        StateService["🔄 State Service"]
    end
    
    %% ============================================
    %% Backend API
    %% ============================================
    BackendAPI["🚀 FastAPI Backend"]
    
    %% ============================================
    %% Component to Root Connections
    %% ============================================
    AppRoot --> ChatComponent
    AppRoot --> WorkspaceComponent
    AppRoot --> WizardComponent
    
    %% ============================================
    %% Feature and Story Connections
    %% ============================================
${featureConnections}${storyConnections}
    
    %% ============================================
    %% State Signal Connections
    %% ============================================
    AppRoot -.-> ChatState
    AppRoot -.-> FeaturesState
    AppRoot -.-> StoriesState
    AppRoot -.-> DiagramsState
    
    ChatComponent -.-> ChatState
    ChatComponent -.-> FeaturesState
    ChatComponent -.-> StoriesState
    
    WorkspaceComponent -.-> FeaturesState
    WorkspaceComponent -.-> StoriesState
    
    %% ============================================
    %% Service Connections
    %% ============================================
    AppRoot --> AgentService
    ChatComponent --> AgentService
    WizardComponent --> AgentService
    
    AppRoot --> LocalStorageService
    ChatComponent --> LocalStorageService
    WorkspaceComponent --> LocalStorageService
    
    AppRoot --> StateService
    StateService -.-> ChatState
    StateService -.-> FeaturesState
    StateService -.-> StoriesState
    StateService -.-> DiagramsState
    
    %% ============================================
    %% API Connections
    %% ============================================
    AgentService --> BackendAPI
    AgentService -->|POST /agent/features| BackendAPI
    AgentService -->|POST /agent/stories| BackendAPI
    AgentService -->|POST /agent/visualizer| BackendAPI
    
    %% ============================================
    %% Enhanced Styling with Colors
    %% ============================================
    classDef rootComponent fill:#7c3aed,stroke:#5b21b6,stroke-width:4px,color:#fff,font-weight:bold
    classDef uiComponent fill:#3b82f6,stroke:#1e40af,stroke-width:2px,color:#fff,font-weight:500
    classDef featureComponent fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef storyComponent fill:#f59e0b,stroke:#d97706,stroke-width:2px,color:#fff,font-weight:500
    classDef stateSignal fill:#8b5cf6,stroke:#6d28d9,stroke-width:2px,color:#fff,font-weight:500
    classDef service fill:#10b981,stroke:#059669,stroke-width:2px,color:#fff,font-weight:500
    classDef api fill:#ef4444,stroke:#dc2626,stroke-width:3px,color:#fff,font-weight:bold
    
    class AppRoot rootComponent
    class ChatComponent,WorkspaceComponent,WizardComponent uiComponent
    ${featureClassNames ? `class ${featureClassNames} featureComponent` : ''}
    ${storyClassNames ? `class ${storyClassNames} storyComponent` : ''}
    class ChatState,FeaturesState,StoriesState,DiagramsState stateSignal
    class AgentService,LocalStorageService,StateService service
    class BackendAPI api
    
    style MainUI fill:#dbeafe,stroke:#3b82f6,stroke-width:2px,stroke-dasharray:5 5
    style Features fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5
    style Stories fill:#fef3c7,stroke:#f59e0b,stroke-width:2px,stroke-dasharray:5 5
    style StateSignals fill:#ede9fe,stroke:#8b5cf6,stroke-width:2px,stroke-dasharray:5 5
    style Services fill:#d1fae5,stroke:#10b981,stroke-width:2px,stroke-dasharray:5 5`;
  }

  static getDBDDiagram(features: any[] = [], stories: any[] = []): string {
    // Dynamic DBD generation based on features and stories
    let dynamicEntities = '';
    let dynamicRelationships = '';
    
    // Add feature-related tables if features exist
    if (features.length > 0) {
      dynamicEntities += `
    
    FEATURE_DETAILS {
        uuid id PK
        uuid feature_id FK
        text problem_statement
        text business_objective
        text user_persona
        json success_metrics
        timestamp created_at
    }`;
      
      dynamicRelationships += `\n    FEATURES ||--o| FEATURE_DETAILS : has_details`;
    }
    
    // Add story-related tables if stories exist
    if (stories.length > 0) {
      dynamicEntities += `
    
    STORY_IMPLEMENTATIONS {
        uuid id PK
        uuid story_id FK
        text implementation_step
        int step_order
        varchar status
        timestamp completed_at
    }`;
      
      dynamicRelationships += `\n    STORIES ||--o{ STORY_IMPLEMENTATIONS : implements`;
    }

    return `erDiagram
    USERS ||--o{ PROJECTS : owns
    PROJECTS ||--o{ FEATURES : includes
    PROJECTS ||--o{ STORIES : contains
    PROJECTS ||--o{ DIAGRAMS : has
    FEATURES ||--o{ STORIES : contains${dynamicRelationships}
    
    USERS {
        uuid id PK
        varchar email UK
        varchar password_hash
        varchar name
        timestamp created_at
        timestamp updated_at
    }
    
    PROJECTS {
        uuid id PK
        uuid owner_id FK
        varchar name
        text idea_prompt
        varchar status
        json metadata
        timestamp created_at
        timestamp updated_at
    }
    
    FEATURES {
        uuid id PK
        uuid project_id FK
        varchar title
        text description
        text acceptance_criteria
        varchar source
        varchar status
        int priority
        timestamp created_at
        timestamp updated_at
    }
    
    STORIES {
        uuid id PK
        uuid feature_id FK
        uuid project_id FK
        text user_story
        text acceptance_criteria
        text implementation_notes
        varchar status
        int story_points
        timestamp created_at
        timestamp updated_at
    }
    
    DIAGRAMS {
        uuid id PK
        uuid project_id FK
        varchar diagram_type
        text mermaid_source
        text svg_cache
        timestamp created_at
        timestamp updated_at
    }${dynamicEntities}`;
  }
}
